package report

import (
	"html/template"
	"io"

	"github.com/Arman-Chaudhury/seaworthy/internal/audit"
)

// WriteHTML renders the self-contained single-file dashboard: inline
// CSS/JS, no external assets (SPEC §7).
func WriteHTML(w io.Writer, findings []audit.Finding, sum Summary, delta *Delta) error {
	type row struct {
		Severity, Rule, Ref, Detail, Message, Hint, Location string
	}
	data := struct {
		Summary Summary
		Delta   *Delta
		Rows    []row
	}{Summary: sum, Delta: delta}
	for _, f := range findings {
		loc := ""
		if f.File != "" {
			loc = template.HTMLEscapeString(f.File)
			if f.Line > 0 {
				loc = loc + ":" + itoa(f.Line)
			}
		}
		data.Rows = append(data.Rows, row{
			Severity: f.Severity.String(),
			Rule:     f.Rule,
			Ref:      f.Ref(),
			Detail:   f.Detail,
			Message:  f.Message,
			Hint:     f.Hint,
			Location: loc,
		})
	}
	return htmlTmpl.Execute(w, data)
}

func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	var b [12]byte
	i := len(b)
	for n > 0 {
		i--
		b[i] = byte('0' + n%10)
		n /= 10
	}
	return string(b[i:])
}

var htmlTmpl = template.Must(template.New("dashboard").Parse(`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>seaworthy report</title>
<style>
  :root { --high:#c62828; --medium:#ef6c00; --low:#1565c0; --ink:#1c2733; --paper:#f6f8fa; }
  * { box-sizing: border-box; }
  body { margin:0; font:15px/1.5 -apple-system,"Segoe UI",Roboto,sans-serif; color:var(--ink); background:var(--paper); }
  header { padding:1.2rem 1.5rem; background:#0b2e4f; color:#fff; }
  header h1 { margin:0; font-size:1.25rem; }
  main { padding:1.5rem; max-width:70rem; margin:0 auto; }
  .tiles { display:flex; gap:.8rem; flex-wrap:wrap; margin-bottom:1.2rem; }
  .tile { flex:1 1 8rem; background:#fff; border-radius:.5rem; padding:.8rem 1rem; border:1px solid #dde3ea; }
  .tile b { display:block; font-size:1.6rem; }
  .tile.high b { color:var(--high); } .tile.medium b { color:var(--medium); } .tile.low b { color:var(--low); }
  .delta { margin:0 0 1.2rem; padding:.7rem 1rem; background:#fff; border:1px solid #dde3ea; border-radius:.5rem; }
  input#q { width:100%; padding:.55rem .8rem; margin-bottom:.8rem; border:1px solid #c8d1db; border-radius:.4rem; font-size:1rem; }
  .tablewrap { overflow-x:auto; background:#fff; border:1px solid #dde3ea; border-radius:.5rem; }
  table { border-collapse:collapse; width:100%; min-width:52rem; }
  th, td { text-align:left; padding:.5rem .8rem; border-top:1px solid #eef1f5; vertical-align:top; }
  th { background:#f0f3f7; border-top:none; font-size:.8rem; text-transform:uppercase; letter-spacing:.04em; }
  .sev { font-weight:700; text-transform:uppercase; font-size:.78rem; }
  .sev.high { color:var(--high); } .sev.medium { color:var(--medium); } .sev.low { color:var(--low); }
  td.rule { font-family:ui-monospace,SFMono-Regular,Menlo,monospace; font-size:.85rem; white-space:nowrap; }
  td.loc { color:#5c6b7a; font-size:.82rem; }
  .hint { color:#5c6b7a; font-size:.85rem; }
  footer { padding:1rem 1.5rem; color:#5c6b7a; font-size:.82rem; }
</style>
</head>
<body>
<header><h1>seaworthy — workload hygiene report</h1></header>
<main>
  <div class="tiles">
    <div class="tile"><b>{{.Summary.Total}}</b>findings</div>
    <div class="tile high"><b>{{.Summary.High}}</b>high</div>
    <div class="tile medium"><b>{{.Summary.Medium}}</b>medium</div>
    <div class="tile low"><b>{{.Summary.Low}}</b>low</div>
    <div class="tile"><b>{{.Summary.Suppressed}}</b>baseline-suppressed</div>
  </div>
  {{if .Delta}}<p class="delta">vs previous run: <b>{{len .Delta.New}}</b> new, <b>{{len .Delta.Fixed}}</b> fixed</p>{{end}}
  <input id="q" type="search" placeholder="filter findings (rule, object, message…)" oninput="flt()">
  <div class="tablewrap"><table id="t">
    <thead><tr><th>Severity</th><th>Rule</th><th>Object</th><th>Message</th><th>Location</th></tr></thead>
    <tbody>
    {{range .Rows}}<tr>
      <td><span class="sev {{.Severity}}">{{.Severity}}</span></td>
      <td class="rule">{{.Rule}}</td>
      <td>{{.Ref}}</td>
      <td>{{.Message}}{{if .Hint}}<div class="hint">{{.Hint}}</div>{{end}}</td>
      <td class="loc">{{.Location}}</td>
    </tr>{{end}}
    </tbody>
  </table></div>
</main>
<footer>generated by seaworthy — findings only, no manifest contents are embedded</footer>
<script>
function flt(){
  var q=document.getElementById('q').value.toLowerCase();
  var rows=document.querySelectorAll('#t tbody tr');
  for(var i=0;i<rows.length;i++){
    rows[i].style.display=rows[i].textContent.toLowerCase().indexOf(q)>=0?'':'none';
  }
}
</script>
</body>
</html>
`))
