apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-seaworthy-read
  labels:
    app.kubernetes.io/name: seaworthy
    app.kubernetes.io/part-of: seaworthy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-seaworthy-read
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-seaworthy
    namespace: {{ .Release.Namespace }}
