apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-seaworthy
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: seaworthy
    app.kubernetes.io/part-of: seaworthy
